; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
	arduino-libraries/NTPClient@^3.2.1
	ayushsharma82/ElegantOTA@^3.1.7
	knolleary/PubSubClient@^2.8
	adafruit/DHT sensor library@^1.4.6
	symlink://../../myesp32
upload_speed = 921600

monitor_speed = 115200
lib_compat_mode = strict
#upload_port = /dev/ttyACM0
#monitor_port = /dev/ttyACM0
#debug_tool = esp-builtin
#upload_protocol = esp-builtin

build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
#    -DCORE_DEBUG_LEVEL=5
#	-DARDUINO_TINYUSB=1

